"""
FastPIFU Inference Report Models

Defines validated Pydantic schemas for deterministic single-letter PIFU
classification reports, including prediction probabilities, safety review
metadata, narrative explanation, and saved report paths.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from pathlib import Path
from typing import Literal

# Pydantic Models
from pydantic import (
    BaseModel,
    Field,
    model_validator,
)


class PIFULabel(StrEnum):
    """Supported PIFU classes."""

    NOT_ELIGIBLE = "NOT_ELIGIBLE"
    BORDERLINE = "BORDERLINE"
    ELIGIBLE = "ELIGIBLE"


PIFU_LABEL_TO_ID = {
    PIFULabel.NOT_ELIGIBLE: 0,
    PIFULabel.BORDERLINE: 1,
    PIFULabel.ELIGIBLE: 2,
}

PIFU_ID_TO_LABEL = {
    label_id: label
    for label, label_id in PIFU_LABEL_TO_ID.items()
}


class PIFUProbabilities(BaseModel):
    """Normalised PIFU class probabilities."""

    not_eligible: float = Field(
        ge=0.0,
        le=1.0,
    )

    borderline: float = Field(
        ge=0.0,
        le=1.0,
    )

    eligible: float = Field(
        ge=0.0,
        le=1.0,
    )

    @model_validator(mode="after")
    def validate_total(self) -> PIFUProbabilities:
        """Check probabilities approximately sum to one."""

        # Probability Sum Check
        total = (
            self.not_eligible
            + self.borderline
            + self.eligible
        )

        if abs(total - 1.0) > 1e-3:
            raise ValueError(
                "PIFU probabilities must sum approximately to 1."
            )

        return self

    def as_label_dict(self) -> dict[PIFULabel, float]:
        """Return probabilities keyed by PIFU label enum."""

        # Label Probability Mapping
        return {
            PIFULabel.NOT_ELIGIBLE: self.not_eligible,
            PIFULabel.BORDERLINE: self.borderline,
            PIFULabel.ELIGIBLE: self.eligible,
        }


class PIFUModelPrediction(BaseModel):
    """Authoritative classifier prediction."""

    predicted_label: Literal[0, 1, 2]
    predicted_class: PIFULabel

    confidence: float = Field(
        ge=0.0,
        le=1.0,
    )

    probabilities: PIFUProbabilities

    @model_validator(mode="after")
    def validate_prediction(self) -> PIFUModelPrediction:
        """Validate class, label, confidence and probability consistency."""

        # Label-Class Consistency Check
        expected_class = PIFU_ID_TO_LABEL[self.predicted_label]

        if self.predicted_class != expected_class:
            raise ValueError(
                "Predicted label and class are inconsistent."
            )

        # Probability Consistency Check
        probability_by_label = self.probabilities.as_label_dict()
        predicted_probability = probability_by_label[self.predicted_class]

        largest_probability = max(
            probability_by_label.values()
        )

        if abs(self.confidence - predicted_probability) > 1e-4:
            raise ValueError(
                "Confidence must equal the predicted class probability."
            )

        if abs(predicted_probability - largest_probability) > 1e-4:
            raise ValueError(
                "Predicted class must have the largest class probability."
            )

        return self


class PIFUSafetyAssessment(BaseModel):
    """Deterministic research review flags."""

    requires_human_review: bool = True
    review_reason: str

    flags: list[str] = Field(default_factory=list)

    confidence_threshold: float = Field(
        ge=0.0,
        le=1.0,
    )

    margin_threshold: float = Field(
        ge=0.0,
        le=1.0,
    )

    top_two_margin: float = Field(
        ge=0.0,
        le=1.0,
    )


class PIFUExplanation(BaseModel):
    """Narrative generated by Pydantic AI."""

    clinical_summary: str

    evidence_summary: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)


class PIFUInferenceReport(BaseModel):
    """Final validated PIFU inference report."""

    run_id: str
    created_at: datetime

    model_name: str
    adapter_path: Path

    text_sha256: str = Field(
        min_length=64,
        max_length=64,
        pattern=r"^[a-fA-F0-9]{64}$",
    )

    prediction: PIFUModelPrediction
    safety: PIFUSafetyAssessment
    explanation: PIFUExplanation

    classifier_authoritative: bool = True
    research_use_only: bool = True
    human_review_required: bool = True

    report_json: Path
    report_markdown: Path

    @model_validator(mode="after")
    def validate_review_flags(self) -> PIFUInferenceReport:
        """Validate report-level human-review flags."""

        # Human Review Consistency
        if self.safety.requires_human_review and not self.human_review_required:
            raise ValueError(
                "human_review_required must be true when safety review is required."
            )

        if not self.research_use_only:
            raise ValueError(
                "FastPIFU inference reports must remain marked as research use only."
            )

        return self